### ISSUE TITLE
Write password to file, make openSSL read it from file and delete the file

### ISSUE THREAD

**Issue by alichtman** [alichtman/macOS-quick-lock#23]
Leaking passwords in command line args is an issue: https://security.stackexchange.com/questions/70911/bash-command-argument-security

Solution: https://unix.stackexchange.com/a/76951

~But, I'm not thrilled about writing the password to a file... If anyone forensically examines the drive, the files will likely come up.~

EDIT: Anyone worried about forensic examination of their drive should be using TAILS, Whonix, Qubes, etc.

~But, assuming any user can see the running processes, the password will be leaked, so I guess that's the lesser of two evils.~

**Comment by shobrook** [comment]
Good idea.

>so I guess that's the lesser of two evils.

Yeah, so let's implement this for our MVP. If this is successful, we'll hopefully attract contributors smarter than ourselves who might have suggestions for improvement.

**Comment by alichtman** [comment]
I actually totally forgot about file permissions. We're fine writing the file to disk as long as we make sure it's only readable by the owner. SSH private keys are stored on disk, too...

**Comment by shobrook** [comment]
Oh, right! Idk how to set file permissions in Javascript though but we'll figure that out.

**Comment by alichtman** [comment]
`600` is the permission we want. `rw` for user, and nothing else.

```js
fs.chmodSync('test.txt', '600');
```

**Comment by alichtman** [comment]
I wish GitHub provided support for forking issues... This will need to be implemented for both the Applescript and the electron app.

Or, do we want the Applescript to be a small wrapper on the electron app? And then we only maintain one codebase?

Notes for Applescript implementation:

```Applescript
" Either this
do shell script

" Or this

    on open theFiles
       repeat with oneFile in theFiles
           tell application "Finder"
               tell oneFile
                   set owner privileges to read write
                   set group privileges to read write
                   set everyones privileges to read write
               end tell
           end tell
       end repeat
    end open
```

**Comment by alichtman** [comment]
This is now irrelevant as we've decided to go with a JS-only implementation.
