### ISSUE TITLE
Got error when encrypting or decrypt files with "(" ")" in filename

### ISSUE THREAD

**Issue by z0ph** [alichtman/macOS-quick-lock#35]
Hello,

Got the following error message when I'm trying to encrypt or decrypt a file with filename containing `"("` AND / OR `")"` chars.

Sample: `Photos (3)`

Encryption was done properly despite the error message, but decrypt was not working at all.

```
The action “Run AppleScript” encountered an error: “sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `cd '/Users/...
```

Thanks

**Comment by alichtman** [comment]
Hm. Interesting. We're currently working on a complete revamp of the app in JS / React / Electron and this problem will probably disappear when we release it. I'll leave this open until then.

**Comment by z0ph** [comment]
Hello, any news on the electron version ? Thanks

**Comment by alichtman** [comment]
Currently still WIP. All the functionality is implemented, we just have to stitch everything together. I don't have an ETA, though.

**Comment by alichtman** [comment]
Closed as no more maintenance will be done on the Applescript version.
