### ISSUE TITLE
Error on encrypt

### ISSUE THREAD

**Issue by amarCosmospace** [alichtman/macOS-quick-lock#36]
hi, i got this issue when i encrypt a file

![image](https://user-images.githubusercontent.com/22593354/73737950-d0d19b00-4743-11ea-91e9-f0fa3ea8bce1.png)

**Comment by alichtman** [comment]
My bet is that the python call in the AppleScript expects a version above 3.0, and you seem to be using 2.7. Try upgrading and give it another shot.

**Comment by amarCosmospace** [comment]
I have python3 installed
![image](https://user-images.githubusercontent.com/22593354/73738342-9e746d80-4744-11ea-9a3e-3127f58b1e55.png)

**Comment by alichtman** [comment]
I'm not sure what else could cause that Python exception to be thrown.
